### ISSUE TITLE
Error: Error in slice3D: begin[0] + size[0] (3) would overflow input.shape[0]

### ISSUE THREAD

**Issue by scraus** [Hyuto/yolov5-tfjs-react-native#1]
I loaded my custom model but I got the ff error even though I already updated the `labels.json`. Is there any file that needs to be updated? 

BTW: My model is YOLOv8. Was that the reason?

![image](https://github.com/Hyuto/yolov5-tfjs-react-native/assets/91582176/3ba60338-8802-42c0-8940-e53b9274e179)

![image](https://github.com/Hyuto/yolov5-tfjs-react-native/assets/91582176/e5dd9c6b-3f9a-4714-8e46-9bf00dbfecec)

**Comment by Hyuto** [comment]
I think the reason is you use YOLOv8 model on this project. YOLOv8 tensorflow model doesn't provide and end2end solution like YOLOv5 so you need to do postprocess the output of model before rendering it. 

You can take a look here for YOLOv8 postprocessing steps to get boxes, scores, and labels to render  https://github.com/Hyuto/yolov8-tfjs/blob/ab4b1326efcf8e8184de5e6a0dcfee7e7864eb08/src/utils/detect.js#L55

**Comment by Hyuto** [comment]
Since there is no further discussion, I'm closing this issue
